<?php
if (!defined('init_pages')) { header('HTTP/1.0 404 not found'); exit; }
$TPL->SetTitle('Videos'); $TPL->AddCSS('template/style/page-media.css'); $TPL->LoadHeader();
function wc_youtube_id_all($url){ if (preg_match('~(?:v=|youtu\.be/|embed/|shorts/|live/)([A-Za-z0-9_-]{6,})~',(string)$url,$m)) return $m[1]; return preg_match('~^[A-Za-z0-9_-]{6,}$~',(string)$url)?$url:''; }
$p = (isset($_GET['p']) ? (int)$_GET['p'] : 1); $CORE->load_CoreModule('paginationType2'); $pagies = new Pagination(); $pagies->addToLink('?page='.$pageName); $perPage = 8;
$res = $DB->prepare('SELECT COUNT(*) FROM `movies` WHERE `status` = 1;'); $res->execute(); $count_row = $res->fetch(PDO::FETCH_NUM); $count = $count_row[0]; unset($count_row,$res);
?>
<div class="content_holder"><div class="sub-page-title"><div id="title"><h1>Media<p></p><span></span></h1></div></div><div class="container_2" align="center" style="padding:30px 40px; width:916px;"><div class="media-header"><h2>VIDEOS</h2><h3 class="items-number">(<?php echo $count; ?>)</h3><div class="clear"></div><div class="bline"></div></div>
<?php if ($count > 0) { $pages = $pagies->calculate_pages($count, $perPage, $p); $res = $DB->query('SELECT `id`,`name`,`short_text`,`youtube` FROM `movies` WHERE `status` = 1 ORDER BY id DESC LIMIT '.$pages['limit'].';'); while ($arr = $res->fetch()) { $yt=wc_youtube_id_all($arr['youtube']); $thumb=$yt?'https://img.youtube.com/vi/'.htmlspecialchars($yt,ENT_QUOTES,'UTF-8').'/mqdefault.jpg':''; echo '<div class="media-video-container media-all-vids-page" align="left"><div class="media-video-thumb container_frame"><div class="cframe_inner"><a href="index.php?page=open-video&id=',(int)$arr['id'],'"><div class="image-thumb-preview" style="background-image:url(\'',$thumb,'\');"></div><div class="play-button-small"></div></a></div></div><div class="video-info"><h3>',htmlspecialchars(stripslashes($arr['name']),ENT_QUOTES,'UTF-8'),'</h3><p style="height:auto;">',htmlspecialchars(stripslashes($arr['short_text']),ENT_QUOTES,'UTF-8'),'</p><a href="index.php?page=open-video&id=',(int)$arr['id'],'" class="youtube-link">Open Video</a></div><div class="clear"></div></div>'; } unset($arr,$res); } else { echo '<p class="there-is-nothing">There are no movies.</p>'; } ?>
<div class="clear"></div><?php if ($count > 0 and $count > $perPage) { echo '<div class="d-cont pagination-holder pagination-media"><ul class="pagination" id="store-pagination">',$pages['first'],$pages['previous'],$pages['info'],$pages['next'],$pages['last'],'</ul><div class="clear"></div></div>'; } unset($pagies,$pages,$count,$perPage,$p); ?></div></div><?php $TPL->LoadFooter(); ?>
